WITH MERCHANT_BILLING_CONTACTS AS
(
SELECT 
	m."NAME" ,
	mc.EMAIL
FROM
	PROD__US.MERCHANTS.MERCHANT m
LEFT JOIN PROD__US.MERCHANTS.MERCHANTCONTACTINFORMATION MC 
	ON
	m.BILLING_CONTACT_ID = mc.ID
) 
SELECT
	cu.ID,
	cu.COMPANYNAME ,
	mbc.Email AS BANKPORTAL_EMAIL
FROM
	FIVETRAN_DATABASE.NETSUITE_SUITEANALYTICS.CUSTOMER cu
JOIN MERCHANT_BILLING_CONTACTS mbc
	ON
	cu.COMPANYNAME = mbc.NAME
WHERE
	cu.BALANCESEARCH > 0
	AND mbc.email IS NOT NULL
	AND mbc.email <> 'testsr@gmail.com'
ORDER BY
	2,
	3