SELECT * FROM FIVETRAN_DATABASE.NETSUITE_SUITEANALYTICS.ACCOUNT

SELECT * FROM FIVETRAN_DATABASE.NETSUITE_SUITEANALYTICS.DEPARTMENT

SELECT * FROM FIVETRAN_DATABASE.NETSUITE_SUITEANALYTICS.LOCATION

SELECT * FROM FIVETRAN_DATABASE.NETSUITE_SUITEANALYTICS.SUBSIDIARY